@startuml

class User {
  +userId : int
  +firstName : string
  +lastName : string
  +login : string
  +password : string
}

class Color {
  +color : string
  +userId : int
}

class LoginAPI {
  +login(login: string, password: string) : JSON
}

class AddColorAPI {
  +addColor(color: string, userId: int) : JSON
}

class SearchColorsAPI {
  +searchColors(search: string, userId: int) : JSON
}

User "1" --> "0..*" Color

LoginAPI ..> User
AddColorAPI ..> Color
SearchColorsAPI ..> Color

@enduml